[colors.bright]
black = "#3b3b3b"
blue = "#8197bf"
cyan = "#8fbfdc"
green = "#99ad6a"
magenta = "#d7afff"
red = "#ffb964"
white = "#ebdbb2"
yellow = "#fad07a"

[colors.cursor]
cursor = "#d8ad4c"
text = "#2a2e2e"

[colors.normal]
black = "#1c1c1c"
blue = "#597bc5"
cyan = "#4a8382"
green = "#99ad6a"
magenta = "#8787af"
red = "#d75f5f"
white = "#e8e8de"
yellow = "#E6C384"

[colors.primary]
background = "#1f1f28"
foreground = "#dcd7ba"

[colors.selection]
background = "#e4e4e4"
text = "#282828"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[scrolling]
history = 10000

[window]
option_as_alt = "Both"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 3
y = 3
