required-version = "==0.16.6"
target-version = "py311"
line-length = 100
indent-width = 4
include = ["*.py"]
extend-exclude = ["target", "dist", "ltui-patch-test"]
preview = false

[lint]
select = ["E4", "E7", "E9", "F", "I", "B"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = false
