local others = {
  -- Language server
  DiagnosticError = { fg = C.red_1 },
  DiagnosticWarn = { fg = C.orange_1 },
  DiagnosticInfo = { fg = C.white_2 },
  DiagnosticHint = { fg = C.yellow_1 },
  DiagnosticUnderlineError = { style = "undercurl", sp = C.red_2 },
  DiagnosticUnderlineWarn = { style = "undercurl", sp = C.red_2 },
  DiagnosticUnderlineInfo = { style = "undercurl", sp = C.red_2 },
  DiagnosticUnderlineHint = { style = "undercurl", sp = C.red_2 },
  LspReferenceText = { fg = C.none, bg = C.grey_5 },
  LspReferenceRead = { fg = C.none, bg = C.grey_5 },
  LspReferenceWrite = { fg = C.none, bg = C.grey_5 },
  LspSagaDiagnosticBorder = { fg = C.white_1 },
  LspSagaSignatureHelpBorder = { fg = C.white_1 },
  LspSagaLspFinderBorder = { fg = C.white_1 },
  LspSagaCodeActionBorder = { fg = C.white_1 },
  LspSagaDefPreviewBorder = { fg = C.white_1 },
  LspSagaHoverBorder = { fg = C.white_1 },
  LspSagaRenameBorder = { fg = C.white_1 },
  LspSagaRenamePromptPrefix = { fg = C.white_1 },
  LspFloatWinBorder = { fg = C.white_1 },
  LspSagaDiagnosticTruncateLine = { fg = C.white_1 },
  LspSagaShTruncateLine = { fg = C.white_1 },
  LspSagaDocTruncateLine = { fg = C.white_1 },
  LspSagaCodeActionTruncateLine = { fg = C.white_1 },
  ProviderTruncateLine = { fg = C.white_1 },
  DiagnosticTruncateLine = { fg = C.white_1, style = "bold" },
  LspSagaCodeActionTitle = { fg = C.yellow, style = "bold" },
  LspSagaCodeActionContent = { fg = C.green, style = "bold" },
  LspFloatWinNormal = { fg = C.fg, bg = C.black_1 },
  LspDiagnosticsFloatingError = { fg = C.red_1 },
  LspDiagnosticsFloatingWarn = { fg = C.orange_1 },
  LspDiagnosticsFloatingInfor = { fg = C.white_2 },
  LspDiagnosticsFloatingHint = { fg = C.yellow_1 },
  LspSagaDiagnosticHeader = { fg = C.yellow },
  LspSagaBorderTitle = { fg = C.yellow, style = "bold" },
  DiagnosticInformation = { fg = C.yellow, style = "bold" },

  -- Treesitter
  TSError = { fg = C.red },
  TSPunctDelimiter = { fg = C.fg },
  TSPunctBracket = { fg = C.fg },
  TSPunctSpecial = { fg = C.fg },
  TSConstant = { fg = C.yellow },
  TSConstBuiltin = { fg = C.orange },
  TSConstMacro = { fg = C.red },
  TSStringRegex = { fg = C.green },
  TSString = { fg = C.green },
  TSStringEscap = { fg = C.red },
  TSCharacter = { fg = C.green },
  TSNumber = { fg = C.orange },
  TSBoolean = { fg = C.orange },
  TSFloat = { fg = C.green },
  TSAnnotation = { fg = C.yellow },
  TSAttribute = { fg = C.red },
  TSNamespace = { fg = C.purple },
  TSFuncBuiltin = { fg = C.blue },
  TSFunction = { fg = C.blue },
  TSFuncMacro = { fg = C.yellow },
  TSParameter = { fg = C.red },
  TSParameterReference = { fg = C.cyan },
  TSMethod = { fg = C.blue },
  TSField = { fg = C.red },
  TSProperty = { fg = C.yellow },
  TSConstructor = { fg = C.yellow },
  TSConditional = { fg = C.purple },
  TSRepeat = { fg = C.purple },
  TSLabel = { fg = C.blue },
  TSKeyword = { fg = C.purple },
  TSKeywordFunction = { fg = C.purple },
  TSKeywordOperator = { fg = C.purple },
  TSOperator = { fg = C.cyan },
  TSException = { fg = C.purple },
  TSType = { fg = C.blue },
  TSTypeBuiltin = { fg = C.blue },
  TSStructure = { fg = C.purple },
  TSInclude = { fg = C.purple },
  TSVariable = { fg = C.red },
  TSVariableBuiltin = { fg = C.yellow },
  TSText = { fg = C.fg },
  TSStrong = { fg = C.fg },
  TSEmphasis = { fg = C.fg },
  TSUnderline = { fg = C.fg },
  TSTitle = { fg = C.fg },
  TSLiteral = { fg = C.fg },
  TSURI = { fg = C.fg },
  TSTag = { fg = C.red },
  TSTagDelimiter = { fg = C.fg },
  rainbowcol1 = { fg = "Gold" },
  rainbowcol2 = { fg = "Orchid" },
  rainbowcol3 = { fg = "LightSkyBlue" },
  rainbowcol4 = { fg = "Gold" },
  rainbowcol5 = { fg = "Orchid" },
  rainbowcol6 = { fg = "LightSkyBlue" },
  rainbowcol7 = { fg = "Orchid" },

  -- Telescope
  TelescopeResultsTitle = { fg = C.green },
  TelescopePromptTitle = { fg = C.blue },
  TelescopePreviewTitle = { fg = C.purple },
  TelescopeResultsBorder = { fg = C.fg },
  TelescopePromptBorder = { fg = C.fg },
  TelescopePreviewBorder = { fg = C.fg },
  TelescopeSelectionCaret = { fg = C.red },
  TelescopeMatching = { fg = C.yellow },
  TelescopeSelection = { bg = C.grey_5 },
  TelescopeMultiSelection = { fg = C.blue },
  TelescopeMultiIcon = { fg = C.blue },
  TelescopeNormal = { fg = C.fg, bg = C.bg },
  TelescopePreviewNormal = { fg = C.fg, bg = C.bg },
  TelescopePromptNormal = { fg = C.fg, bg = C.bg },
  TelescopeResultsNormal = { fg = C.fg, bg = C.bg },
  TelescopeBorder = { fg = C.fg },
  TelescopeTitle = { fg = C.fg },
  TelescopePromptCounter = { fg = C.grey_1 },
  TelescopePromptPrefix = { fg = C.blue },
  TelescopePreviewLine = { bg = C.grey_5 },
  TelescopePreviewMatch = { fg = C.yellow },
  TelescopePreviewPipe = { fg = C.yellow },
  TelescopePreviewCharDev = { fg = C.yellow },
  TelescopePreviewDirectory = { fg = C.blue },
  TelescopePreviewBlock = { fg = C.yellow },
  TelescopePreviewLink = { fg = C.blue },
  TelescopePreviewSocket = { fg = C.purple },
  TelescopePreviewRead = { fg = C.yellow },
  TelescopePreviewWrite = { fg = C.purple },
  TelescopePreviewExecute = { fg = C.green },
  TelescopePreviewHyphen = { fg = C.grey_1 },
  TelescopePreviewSticky = { fg = C.blue },
  TelescopePreviewSize = { fg = C.green },
  TelescopePreviewUser = { fg = C.yellow },
  TelescopePreviewGroup = { fg = C.yellow },
  TelescopePreviewDate = { fg = C.blue },
  TelescopePreviewMessage = { fg = C.fg },
  TelescopePreviewMessageFillchar = { fg = C.fg },
  TelescopeResultsClass = { fg = C.yellow },
  TelescopeResultsConstant = { fg = C.yellow },
  TelescopeResultsField = { fg = C.red },
  TelescopeResultsFunction = { fg = C.blue },
  TelescopeResultsMethod = { fg = C.blue },
  TelescopeResultsOperator = { fg = C.cyan },
  TelescopeResultsStruct = { fg = C.purple },
  TelescopeResultsVariable = { fg = C.red },
  TelescopeResultsLineNr = { fg = C.grey_1 },
  TelescopeResultsIdentifier = { fg = C.blue },
  TelescopeResultsNumber = { fg = C.orange },
  TelescopeResultsComment = { fg = C.grey_2 },
  TelescopeResultsSpecialComment = { fg = C.grey },
  TelescopeResultsDiffChange = { fg = C.none, bg = C.yellow },
  TelescopeResultsDiffAdd = { fg = C.none, bg = C.green },
  TelescopeResultsDiffDelete = { fg = C.none, bg = C.red },
  TelescopeResultsDiffUntracked = { fg = C.none, bg = C.grey_1 },

  -- NvimTree
  NvimTreeFolderIcon = { fg = C.blue },
  NvimTreeExecFile = { fg = C.green },
  NvimTreeOpenedFile = { fg = C.green },
  NvimTreeRootFolder = { fg = C.bg },
  NvimTreeEndOfBuffer = { fg = C.bg },
  NvimTreeNormal = { bg = C.blue_2 },
  NvimTreeNormalNC = { bg = C.blue_2 },
  NvimTreeVertSplit = { fg = C.blue_2, bg = C.blue_2 },
  NvimTreeImageFile = { fg = C.purple },
  NvimTreeSymlink = { fg = C.cyan },
  NvimTreeSpecialFile = { fg = C.yellow },
  NvimTreeGitDeleted = { fg = C.red },
  NvimTreeGitMerge = { fg = C.orange },
  NvimTreeGitRenamed = { fg = C.purple },
  NvimTreeGitStaged = { fg = C.green },
  NvimTreeGitDirty = { fg = C.red },
  NvimTreeGitNew = { fg = C.yellow },

  -- VimWiki
  VimwikiLink = { fg = C.cyan, bg = C.none },
  VimwikiHeaderChar = { fg = C.grey, bg = C.none },
  VimwikiHR = { fg = C.yellow, bg = C.none },
  VimwikiList = { fg = C.orange, bg = C.orange },
  VimwikiTag = { fg = C.orange, bg = C.orange },
  VimwikiMarkers = { fg = C.grey, bg = C.none },
  VimwikiHeader1 = { fg = C.orange, bg = C.none, style = "bold" },
  VimwikiHeader2 = { fg = C.green, bg = C.none, style = "bold" },
  VimwikiHeader3 = { fg = C.blue, bg = C.none, style = "bold" },
  VimwikiHeader4 = { fg = C.cyan, bg = C.none, style = "bold" },
  VimwikiHeader5 = { fg = C.yellow, bg = C.none, style = "bold" },
  VimwikiHeader6 = { fg = C.purple, bg = C.none, style = "bold" },

  -- IndentBlankLine
  IndentBlanklineSpaceChar = { fg = C.grey_6, style = "nocombine" },
  IndentBlanklineChar = { fg = C.grey_6, style = "nocombine" },
  IndentBlanklineContextStart = { fg = C.grey_7, style = "underline" },
  IndentBlanklineContextChar = { fg = C.grey_7, style = "nocombine" },
  IndentBlanklineSpaceCharBlankline = { fg = C.grey_6, style = "nocombine" },

  -- GitSigns
  GitSignsAdd = { fg = C.green, bg = C.none },
  GitSignsChange = { fg = C.orange_1, bg = C.none },
  GitSignsDelete = { fg = C.red_1, bg = C.none },
  MoreMsg = { fg = C.green, style = "bold" },
  ModeMsg = { fg = C.grey, style = "bold" },

  -- Hop
  HopNextKey = { fg = C.red, style = "bold" },
  HopNextKey1 = { fg = C.cyan, style = "bold" },
  HopNextKey2 = { fg = C.blue },
  HopUnmatched = { fg = C.grey },

  -- Lightspeed
  LightspeedLabel = { fg = C.red_3, style = "underline" },
  LightspeedLabelOverlapped = { fg = C.blue, style = "underline" },
  LightspeedLabelDistant = { fg = C.red_1, style = "underline" },
  LightspeedLabelDistantOverlapped = { fg = C.blue_1, style = "underline" },
  LightspeedShortcut = { fg = C.black, bg = C.red_3, style = "bold,underline" },
  LightspeedShortcutOverlapped = { fg = C.black, bg = C.blue, style = "bold,underline" },
  LightspeedMaskedChar = { fg = C.green_1 },
  LightspeedGreyWash = { fg = C.grey_2, bg = C.none },
  LightspeedUnlabeledMatch = { fg = C.white, style = "bold" },
  LightspeedOneCharMatch = { fg = C.green, bg = C.red_3, style = "bold" },
  LightspeedUniqueChar = { fg = C.white, style = "bold" },
  LightspeedPendingOpArea = { fg = C.yellow },

  -- WhichKey
  WhichKeyFloat = { fg = C.fg },
  WhichKeyDesc = { fg = C.blue },
  WhichKeyGroup = { fg = C.blue },

  -- SymbolsOutline
  FocusedSymbol = { fg = C.yellow, bg = C.none },
}

return others
