#! /bin/sh
#----------------------------- ~bspwmrc~ ------------------------------#

xsetroot -cursor_name left_ptr
setroot --blank-color "#2E3440"

#----------------------------- ~monitor~ ------------------------------#

# ~set xrandr~ (dual monitor support)
#if [ -x $HOME/scripts/monitor/dual_monitor ];then
#    $HOME/scripts/monitor/dual_monitor
#fi

# ~wmname|LG3D~ (fixes screentearing with gui apps)
wmname LG3D

# ~set desktops~
bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

#----------------------------- ~window~ -------------------------------#

bspc config border_width         2
bspc config window_gap           20
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  "#7c6f64"

#----------------------------- ~startup~ ------------------------------#

# ~sxhkd~ (hotkey manager)
killall sxhkd; sxhkd &

# ~picom~ (compositor)
killall picom; picom &

# ~dunst~ (notification manager)
killall dunst; dunst &

# ~polybar~ (status bar)
killall -q polybar; $HOME/.config/polybar/launch.sh

killall xob; xob &

# ~xresources~ (load)
xrdb -load ~/.Xresources

# ~feh~ (wallpaper manager)
feh --bg-fill ~/Documents/Wallpapers/bg1.jpg

# ~betterlockscreen~ (fetch background image)
sudo betterlockscreen -u ~/Documents/Wallpapers/bg1.jpg

# ~xset~ (key-repeat speed)
xset r rate 250 40

# ~setxkbmap~ (us/sv layout - toggle with alt+shift)
setxkbmap -layout us,se -option grp:alt_shift_toggle

#------------------------------ ~rules~ -------------------------------#

# ~zathura~
bspc rule -a zathura state=tiled

mkdir "$XOBPIPES"
mkfifo "$XOBPIPES/bkl"; pkill -f "tail -f $XOBPIPES/bkl"; tail -f "$XOBPIPES/bkl" | xob &
mkfifo "$XOBPIPES/kbd"; pkill -f "tail -f $XOBPIPES/kbd"; tail -f "$XOBPIPES/kbd" | xob &
mkfifo "$XOBPIPES/vol"; pkill -f "tail -f $XOBPIPES/vol"; tail -f "$XOBPIPES/vol" | xob &
